__title__ = 'L-layer Neural Network'
__version__ = '0.0.1'
__author__ = 'Sverre van Gompel'
__description__ = 'Deep Neural Network experiment'
__url__ = 'https://github.com/Van-Gompel-AI/L-layer-Neural-Network'
